### PR TITLE
Mico - Learn Fork Git Client

### PR DESCRIPTION
**Pull request by micoespina**
Added Comment

### CODE REVIEW

**Review by titozer — APPROVED** [review]
Ok sakin

**Review by titojp — APPROVED** [review]
Ok

**Review by TitaBea — COMMENTED** [review]
Pogi mo Mico!

**Review by TitaBea — APPROVED** [review]
Approved na po ba?

**Review by TitaBea — CHANGES_REQUESTED** [review]
Request

**Review by TitaBea — APPROVED** [review]

**Pull request merged**
